server:
  port: 8401
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: huidong
    password: xhd!0707
    url: "jdbc:mysql://rm-uf60cb427hat3ys25fo.mysql.rds.aliyuncs.com:3306/user_center?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&verifyServerCertificate=false&useSSL=false"
  application:
    name: user-center
  cloud:
    nacos:
      discovery:
        server-addr: 139.196.196.1:1111
    sentinel:
      transport:
        dashboard: localhost:8088
        port: 8719   #默认8719端口，假如被占用会自动从8719开始一次扫面，直至找到未被占用的端口
    stream:
      rocketmq:
        binder:
          name-server: 127.0.0.1:9876
      bindings:
        input:
          destination: stream-test-topic
          group: binder-group #这里一定要设置，如果用的是其他的mq可以不设置

#消费者将要去访问的微服务名称（注册成功进nacos的微服务提供者）
#service-url:
#  nacos-user-service: http://nacos-payment-provider
#激活sentinel对openFeign的支持
feign:
  sentinel:
    enabled: true
#rocketmq:
#  name-server: 127.0.0.1:9876