server:
  port: 9527
spring:
  zipkin:
    base-url: http://localhost:9411/
    discovery-client-enabled: false
  sleuth:
    sampler:
      probability: 1.0   #抽样率，默认 0.1
  application:
    name:  gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true   #让gateway通过服务发现找到其他的微服务
      routes:
        - id: user_route   #路由的ID，没有固定规则但要求唯一#uri: http://localhost:8001  #匹配后提供服务的路由地址
          uri: lb://user-center #匹配后提供服务的路由地址
          predicates:
            - Path=/users/**      #断言，路径相匹配的进项路由
        - id: content_route
          uri: lb://content-center
          predicates:
            - Path=/shares/** ,/admin/**
    nacos:
      discovery:
        server-addr: 139.196.196.1:1111
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'